config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get '/top' => 'homes#top'
post '/articles' => 'articles#create'
get '/articles' => 'articles#index'
get '/articles/:id' => 'articles#show', as: 'article'
root :to => 'homes#top'
get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'
patch '/articles/:id' => 'articles#update', as: 'update_article'
delete '/articles/:id' => 'articles#destroy', as: 'destroy_article'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    attachment :image
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  	@article = Article.new
 end
    def create
  	article = Article.new(articles_params)
  	article.save
  	redirect_to article_path(article.id)
  end

  def index
  	@articles = Article.all
  	@article = Article.new
  end
  def show
  	@article = Article.find(params[:id])
  end
  def edit
        @article = Article.find(params[:id])
  end
  def update
  	article = Article.find(params[:id])
    article.update(article_params)
    redirect_to article_path(article.id)
  end
  def destroy
  	article = Article.find(params[:id])
    article.destroy
    redirect_to articles_path
  end
  private
  def articles_params
  	params.require(:article).permit(:title, :body, :weather, :image)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top

	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@post = Post.new
  end
  def create
  	post = Post.new(post_params)
  	post.save
  	redirect_to post_path(post.id)
  end
  def index
  	@posts = Post.all
  end
  def show
  	@post = Post.find(params[:id])
  end
  def edit
        @post = Post.find(params[:id])
    end
   private
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/edit.html.erb
<h1>編集画面</h1>

<%= form_for(@article) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>天気</h4>
    <%= f.text_area :weather %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>    
<% end %>

app/views/articles/index.html.erb
<ul class="nav nav-tabs">
	<li role="presentation" class="active"><a href="#">ホーム</a></li>
	<li role="presentation"><a href="#">メニューＡ</a></li>
	<li role="presentation"><a href="#">メニューＢ</a></li>
</ul>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
			<h1>新規投稿</h1>
<%= form_for(@article) do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title %>
 
    <h4>本文</h4>
    <%= f.text_area :body %>


    <h4>天気</h4>
    <%= f.text_area :weather %>

    <h4>画像</h4>
    <%= f.attachment_field :image %>

    <%= f.submit '投稿' %>
 
<% end %>
		</div>
		<div class="col-md-8">
			<h1>投稿一覧</h1>
			<table class="table">
	<thead>
	<tr>
		<th>タイトル</th>
		<th>天気</th>
		<th>本文</th>
		<th>投稿した時間</th>
	</tr>
</thead>
<tbody>
	<% @articles.each do |article| %>

	<tr>
		<td>
			<p>
				<%=link_to article.title, "/articles/#{article.id}" %>
			</p>
		</td>
		<td>
			<p>
				<%=link_to article.weather, "/articles/#{article.id}" %>
			</p>
		</td>
		<td>
			<p>
				<%=link_to article.body, "/articles/#{article.id}" %>
			</p>
		</td>
		<td>
			<p>
				<%=link_to article.created_at, "/articles/#{article.id}" %>
			</p>
		</td>
		<td>
		    <p>
                <%= attachment_image_tag article, :image, :fill, 100, 100, format: 'jpeg' %>
            </p>
        </td>
	</tr>
    <% end %>
	</tbody>
	</table>
   
	</div>
</div>
</div>


app/views/articles/new.html.erb
<h1>新規投稿</h1>
<%= form_for(@article) do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title %>
 
    <h4>本文</h4>
    <%= f.text_area :body %>


    <h4>天気</h4>
    <%= f.text_area :weather %>

    <h4>画像</h4>
    <%= f.attachment_field :image %>
 

  <%= f.submit '投稿' %>
 
<% end %>

app/views/articles/show.html.erb
<h2>タイトル</h2>
<p><%= @article.title %></p>
<h2>本文</h2>
<p><%= @article.body %></p>
<h2>天気</h2>
<p><%= @article.weather %></p>
<h2>画像</h2>
<%= attachment_image_tag @article, :image, :fill, 300, 300, format: 'jpeg' %>

<%= link_to "編集する", edit_article_path(@article.id) %>
<%= link_to "一覧へ戻る", articles_path %>
<%= link_to "削除", destroy_article_path(@article.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

app/views/homes/img.html.erb
<%= image_tag '/assets/taiko.jpg'%>

app/views/homes/top.html.erb
<h1>moeko terasawa</h1>
<%= image_tag '/assets/taiko.jpg'%>
<%= link_to '新規投稿ページに行く', articles_new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoekoDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
 <% @posts.each do |post| %>
    <p>タイトル</p>
    <span>
    <%=link_to post.title, post_path(post.id)%>
    </span>
 <% end %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@post) do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title %>
 
    <h4>本文</h4>
    <%= f.text_area :body %>
 
    <%= f.submit '投稿' %>
 
<% end %>

app/views/posts/show.html.erb
<h2>タイトル</h2>
<p><%= @post.title %></p>
<h2>本文</h2>
<p><%= @post.body %></p>